# Generated by Django 5.2.14 on 2026-05-27 11:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_smartchunk_context_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_doc_category_ref_id_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy display string; mirrors Category.name when category_ref is set.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_summary',
            field=models.TextField(blank=True, help_text='Resumen automático del archivo al ingerirlo (para RAG y documentos relacionados). Distinto del campo `description`, que suele ser manual.'),
        ),
        migrations.AlterField(
            model_name='smartchunk',
            name='content_norm',
            field=models.GeneratedField(db_persist=True, expression=models.Func(django.db.models.functions.text.Lower(models.F('content')), function='immutable_unaccent'), output_field=models.TextField()),
        ),
    ]
