# Generated by Django 5.2.8 on 2025-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='project_pro_owner_i_bc287f_idx',
            old_name='project_own_created_aa3a57_idx',
        ),
    ]
