# Generated by Django 5.2.14 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_skill_pinned_document_slugs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skill',
            new_name='skill_skill_owner_i_0d5f3f_idx',
            old_name='skill_skill_owner_type_idx',
        ),
        migrations.RenameIndex(
            model_name='skillexecution',
            new_name='skill_skill_owner_i_763a95_idx',
            old_name='skill_exec_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='skillexecution',
            new_name='skill_skill_skill_i_fd0fe4_idx',
            old_name='skill_exec_skill_status_idx',
        ),
        migrations.RenameIndex(
            model_name='skillexecutionversion',
            new_name='skill_skill_executi_b5199c_idx',
            old_name='skill_skil_executi_v_idx',
        ),
        migrations.AlterField(
            model_name='skill',
            name='allowed_contexts',
            field=models.JSONField(default=list, help_text='List of allowed contexts, e.g. ["repository", "project", "document"]'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='prompt_template',
            field=models.TextField(blank=True, help_text='For QUICK skills: use {{context}} to inject document content and {{extra_instructions}} for optional user instructions.'),
        ),
        migrations.AlterField(
            model_name='skillexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skillexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillexecutionversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skillstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skillstep',
            name='instructions',
            field=models.TextField(help_text='What the AI should produce for this section of the output.'),
        ),
    ]
