# Generated by Django 5.2.14 on 2026-05-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repositoryshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='repository',
            new_name='repository__repo_ty_2d7ad4_idx',
            old_name='repository__repo_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='repository',
            new_name='repository__owner_i_dfccc1_idx',
            old_name='repository__owner_cr_idx',
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null for Ecofilia-managed PUBLIC repositories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorydocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When False the document is excluded from chat and skill runs.'),
        ),
    ]
