# Generated by Django 5.2.8 on 2025-11-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_session_70d41b_idx',
            old_name='chat_chatm_session_feb991_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_chatse_owner_i_483ab8_idx',
            old_name='chat_chats_owner__35822a_idx',
        ),
    ]
