# Generated by Django 5.2.14 on 2026-05-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_owner_updated_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_chatse_primary_a3d36a_idx',
            old_name='chat_chats_primary_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_chatse_project_237fad_idx',
            old_name='chat_chats_project_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chat_chatse_reposit_831489_idx',
            old_name='chat_chats_reposit_owner_idx',
        ),
    ]
