# Generated by Django 5.2.14 on 2026-05-27 11:12

import apps.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_approved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
    ]
